# Generated by Django 4.1.3 on 2022-11-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('is_kid_home', models.IntegerField()),
                ('where_is_kid', models.CharField(max_length=10)),
                ('is_kid_ready', models.CharField(max_length=10)),
                ('schedule_uri', models.CharField(max_length=10)),
                ('stage_uri', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_dt', models.JSONField(default='')),
            ],
        ),
    ]
